module.exports = [
	["auth", "isLogin"],
	["auth", "logout"],
	["user", "getUserInfo"],
	["user", "editUserInfo"],
	["user", "setPhone"],
	["user", "setPushClientId"],
	['push'],
	['menu', 'getMenu'],
	['product', 'getProductById'],
	['product', 'saveProduct'],
	['product', 'deleteProductByIds'],
	['product', 'getProducts'],
	['message', 'setMessageRead'],
	['message', 'getMessageById'],
	['message', 'addMessage'],
	['message', 'deleteMessageByIds'],
	['message', 'getMessages'],
]